name: wednesdaydemo
recipe: pantheon
config:
  webroot: web
  framework: drupal8
  env: dev
  site: wednesdaydemo
  id: e053cde0-a2a9-4965-8af9-d9c692beb6b5
services:
  appserver:
    overrides:
      services:
        environment:
          BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://nginx/"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/web" }}}}'
tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
